# Generated by Django 4.2.1 on 2023-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sociallinkstype_team_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='about/')),
                ('since', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('bottom_picture', models.ImageField(upload_to='about_banner/')),
            ],
        ),
    ]
